origin = "https://local-authority-eng.register.gov.uk"
name = "Local authorities in England"
description = "Local authorities in England"
publication_date = "2018-11-11"
id = "local-authority-england"
organisation = { id = "govuk", name = "The UK Government" }
owner = { id = "MHCLG", name = "Ministry of Housing, Communities and Local Government" }
copyright_holder = { id = "crown", name = "The Crown" }
license = "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"

versions = {latest = true, pinned = []}

[schema]
primary_key = ["_id"]

[[schema.attributes]]
id = "_checksum"
datatype = "string"
required = true

[[schema.attributes]]
id = "key"
alias = "_id"
datatype = "string"
format = "[A-Z]{3,4}"
required = true

[[schema.attributes]]
id = "name"
datatype = "string"
required = true

[[schema.attributes]]
id = "official-name"
alias = "official_name"
datatype = "string"

[[schema.attributes]]
id = "citizen-names"
alias = "citizen_names"
datatype = "string"
separator = ";"

[[schema.attributes]]
id = "start-date"
alias = "start_date"
format = "yyyy-MM-dd"
datatype = "date"

[[schema.attributes]]
id = "end-date"
alias = "end_date"
format = "yyyy-MM-dd"
datatype = "date"
